
name: 'Integration Test: Installation and Entry'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  install-and-entry:
    runs-on: ubuntu-latest
    steps:

      - name: Download install script from github and run it with local bash
        run: curl -o- "https://raw.githubusercontent.com/jan9won/git-wip-commit/main/install.bash" | bash 
        
      - name: Run entry script with argument "help"
        run: mkdir ~/test | cd ~/test | git init | git wip help
